# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import devicehost_pb2 as devicehost__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in devicehost_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceHostStub:
    """DeviceHost is a host exposing device types that evcc configures and instantiates
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Types = channel.unary_unary(
                '/devicehost.DeviceHost/Types',
                request_serializer=devicehost__pb2.TypesRequest.SerializeToString,
                response_deserializer=devicehost__pb2.TypesReply.FromString,
                _registered_method=True)
        self.New = channel.unary_unary(
                '/devicehost.DeviceHost/New',
                request_serializer=devicehost__pb2.NewRequest.SerializeToString,
                response_deserializer=devicehost__pb2.NewReply.FromString,
                _registered_method=True)
        self.Call = channel.unary_unary(
                '/devicehost.DeviceHost/Call',
                request_serializer=devicehost__pb2.CallRequest.SerializeToString,
                response_deserializer=devicehost__pb2.CallReply.FromString,
                _registered_method=True)


class DeviceHostServicer:
    """DeviceHost is a host exposing device types that evcc configures and instantiates
    """

    def Types(self, request, context):
        """Types returns the device types this host can instantiate
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def New(self, request, context):
        """New instantiates a device type from configuration properties
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Call(self, request, context):
        """Call invokes a capability method on an instantiated device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceHostServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Types': grpc.unary_unary_rpc_method_handler(
                    servicer.Types,
                    request_deserializer=devicehost__pb2.TypesRequest.FromString,
                    response_serializer=devicehost__pb2.TypesReply.SerializeToString,
            ),
            'New': grpc.unary_unary_rpc_method_handler(
                    servicer.New,
                    request_deserializer=devicehost__pb2.NewRequest.FromString,
                    response_serializer=devicehost__pb2.NewReply.SerializeToString,
            ),
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=devicehost__pb2.CallRequest.FromString,
                    response_serializer=devicehost__pb2.CallReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'devicehost.DeviceHost', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('devicehost.DeviceHost', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceHost:
    """DeviceHost is a host exposing device types that evcc configures and instantiates
    """

    @staticmethod
    def Types(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devicehost.DeviceHost/Types',
            devicehost__pb2.TypesRequest.SerializeToString,
            devicehost__pb2.TypesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def New(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devicehost.DeviceHost/New',
            devicehost__pb2.NewRequest.SerializeToString,
            devicehost__pb2.NewReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devicehost.DeviceHost/Call',
            devicehost__pb2.CallRequest.SerializeToString,
            devicehost__pb2.CallReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
